#!/bin/sh
# referenced from https://github.com/tatsuru/isucon13/blob/main/scripts/deploy
# 
# Command Usage
# ./scripts/deploy branch_name server_name
# ./scripts/deploy v1.0.4 kackey0-1
# 
set -v

##### 引数関連
# 引数でブランチ名を受け取る。デフォルトは 'master'
branch=${1:-master}
# 引数で対象サーバーを受け取る。複数サーバーを指定可能
servers=${@:2}
##### 引数終了

##### Basic Settings
BASEDIR="/home/isucon/isucon12-final"
APP_NAME="isuconquest"
DEPLOY_DIR="/home/isucon/webapp/go/${APP_NAME}"

now=$(date +%Y%m%d-%H%M%S)
#####


update="cd ${BASEDIR} && git remote update && git checkout $branch"
update_mysqld_config="sudo cp ${BASEDIR}/mysql/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf"
disable="sudo systemctl disable $APP_NAME.go.service && sudo systemctl stop $APP_NAME.go.service && sudo systemctl disable nginx && sudo systemctl stop nginx"
rotate_mysql="sudo touch /var/log/mysql/mysql-slow.log && sudo mv -v /var/log/mysql/mysql-slow.log /var/log/mysql/mysql-slow.log.$now && mysqladmin -uisucon -pisucon flush-logs && sudo systemctl restart mysql"

# サーバーに順次デプロイ
for server in $servers; do
  echo "Deploying to $server"
  # ssh -A isucon@54.95.112.73 "$update && $restart && $rotate_mysql && $rotate_nginx"
  ssh -A isucon@$server "$update && $disable && $update_mysqld_config && $rotate_mysql"
done

